import {
  type DataPointDefinition,
  type Webhook,
} from '@awell-health/extensions-core'
import { type settings } from '../settings'

const dataPoints = {
  eventType: {
    key: 'eventType',
    valueType: 'string',
  },
  hello: {
    key: 'hello',
    valueType: 'string',
  },
} satisfies Record<string, DataPointDefinition>

// Payload must be exported so it can be included in the declaration file generated by the build script
export interface Payload {
  eventType: string
  hello: string
}

export const demo: Webhook<keyof typeof dataPoints, Payload, typeof settings> =
  {
    key: 'demo',
    dataPoints,
    onEvent: async ({
      payload: { payload, headers, rawBody, settings },
      onSuccess,
      onError,
      helpers,
    }) => {
      const signingSecret = headers['x-signing-secret']
      if (signingSecret == null || signingSecret !== settings.secret) {
        await onError({
          response: { statusCode: 401, message: 'Unauthorized' },
        })
        return
      }
      const { eventType, hello } = payload
      await onSuccess({
        data_points: {
          eventType,
          hello,
        },
      })
    },
  }

// Unnecessary, but included to help with type inference and consistency
export type Demo = typeof demo
